PACKAGE_NAME="victus-keyboard-hp-wmi"
PACKAGE_VERSION="1.1.0"
MAKE[0]="bash $dkms_tree/$module/$module_version/build/build-module.sh $kernel_source_dir $dkms_tree/$module/$module_version/build"
CLEAN="make -C $kernel_source_dir M=$dkms_tree/$module/$module_version/build clean"
BUILT_MODULE_NAME[0]="hp-wmi"
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"
